### ISSUE TITLE
如果window系统无法运行，请修改下ApkResigner.py

### ISSUE THREAD

**Issue by tomatoxman** [Jay-Goo/ProtectedApkResignerForWalle#1]
最后一行添加个括号
print "\n**** Finish! Please Check the 'Channels' Folder in your root Floder ! ****\n"
改为
print("Finish! Please Check the 'Channels' Folder in your root Floder !")

**Comment by JinJieGu** [comment]
@eric721 和系统无关，应该是python版本问题，我作下兼容吧。多谢意见
