### ISSUE TITLE
win10 执行py文件报错

### ISSUE THREAD

**Issue by lu-xu** [Jay-Goo/ProtectedApkResignerForWalle#14]
$ python ApkResigner.py
  File "ApkResigner.py", line 135
    print "\n**** =============================TASK FINISHED=================================== ****\n"
                                                                                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n**** =============================TASK FINISHED=================================== ****\n")?

给print加上括号就好了

print( "\n**** =============================TASK FINISHED=================================== ****\n")
print( "\n↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓   Please check channels in the path   ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓\n")
print ("\n"+channelsOutputFilePath+"\n")
print ("\n**** =============================TASK FINISHED=================================== ****\n")

**Comment by JinJieGu** [comment]
恩，应该和python版本有关，下个future我会做一个兼容进去，也欢迎提PR

**Comment by lu-xu** [comment]
建议在readme里写清楚python版本。毕竟2.x和3.x有挺大不同的，我用的3.6.5
