### ISSUE TITLE
MAC 版本下无法使用

### ISSUE THREAD

**Issue by Event16** [Jay-Goo/ProtectedApkResignerForWalle#15]
你好 我再mac上面配置之后无法生成 ，能否方便提供下qq 加我也行  185200639  thks

**Comment by JinJieGu** [comment]
请提供下你的配置文件，和python版本

**Comment by Event16** [comment]
已经解决了  完美生成渠道文件   之前Win使用的是下面这三个路径么有设置一样可以  现在我是昨天下载的，没想到必须添加这三个路径
#加固后的源文件所在文件夹路径(...path),注意结尾不要带分隔符，默认在此文件夹根目录
protectedSourceApkDirPath = ""
#渠道包输出路径，默认在此文件夹Channels目录下
channelsOutputFilePath = ""
#渠道名配置文件路径，默认在此文件夹根目录
channelFilePath = ""

作者回复的真迅速啊  给作者点赞！thks

**Comment by JinJieGu** [comment]
哈哈，问题解决了就好！祝你使用愉快~
