### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by PengsongAndroid** [Jay-Goo/ProtectedApkResignerForWalle#2]
执行python 出现这个异常 java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool : Unsupported major.minor version 52.0

请问下大佬 工具编译的 jdk的版本是多少

**Comment by JinJieGu** [comment]
@PengsongAndroid 你的sdkBuildTool是多少？请使用25.0+的版本，相关路径在config.py中配置下

**Comment by PengsongAndroid** [comment]
@JinJieGu 25.0.3 已经都配置过了

**Comment by PengsongAndroid** [comment]
@JinJieGu 问题解决了 升级java1.8就可以正常打包了

**Comment by JinJieGu** [comment]
@PengsongAndroid 这个工具使用python写的，只要拥有python环境即可，不受jdk版本影响，应该是你本地配置的一些问题。
给你一些建议，你尝试下：
1、 保证你Android程序的compileSdKVersion 和 buildToosVersion 版本相同
2、建议将jdk升级到1.8
3、保证自己本地打包签名可以正常运行
