### ISSUE TITLE
华为8.0解析失败

### ISSUE THREAD

**Issue by yangdong125845** [Jay-Goo/ProtectedApkResignerForWalle#21]
App内应用升级 华为8.0解析失败

**Comment by moyergo** [comment]
我的也是，华为mate20说没有任何证书，小米8说解析失败，小米应用市场都审核失败了，说应用不能安装。

**Comment by JinJieGu** [comment]
解析失败可能是walle的问题，这个工具已经是最新的walle-cli，我也会及时关注更新的。至于应用不能安装应该不至于，请检查下是否做了其他的操作
