### ISSUE TITLE
打包出来的APK，Play 保存不了，Google 也没提示信息

### ISSUE THREAD

**Issue by gavinliu** [Jay-Goo/ProtectedApkResignerForWalle#22]

**Comment by JinJieGu** [comment]
不太明白什么意思，请详细描述

**Comment by gavinliu** [comment]
我关了吧，换项目了，没有测试环境了。

当时是 乐固 + walle ，传到 Google Play 校验就是通不过，APK 是可以安装，签名啥也是对的。用乐固直接输出的就没问题。

我也尝试自己写针对 walle 的签名脚本，也通不过，最后放弃了，直接用乐固的多渠道打包了。
