### ISSUE TITLE
jks格式的key不支持吗?

### ISSUE THREAD

**Issue by NicodeLee** [Jay-Goo/ProtectedApkResignerForWalle#25]
错误信息   
 import config
  File "E:\GitHub\ProtectedApkResignerForWalle\config.py", line 6
    keystorePath = "E\:\\job\\xdk\\app\xdk.jks"
                  ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 26-28: truncated \xXX escape

**Comment by Jack-Xiao** [comment]
注意要转移的字符吧

**Comment by JinJieGu** [comment]
支持的
