### ISSUE TITLE
按照你的步骤，重签名渠道写不进去，安装运行获取不到渠道号

### ISSUE THREAD

**Issue by xuehuashi** [Jay-Goo/ProtectedApkResignerForWalle#3]

**Comment by xuehuashi** [comment]
按这个命令行操作可以http://18e0c209.wiz01.com/share/s/0oUc890scQDx2tkMAj02NI0c3Ubmms31ckdr2UwE0E2X-bzY

**Comment by JinJieGu** [comment]
@xuehuashi  额，what happen?

**Comment by xsslong** [comment]
什么情况, 怎么就 Closed了, 都没个说明. 我这边生成了encrypted_aligned.apk和encrypted_aligned_signed.apk两个包, 但还是获取不到渠道号, 不知道什么情况

**Comment by JinJieGu** [comment]
@xsslong 麻烦把报错的日志贴一下
