### ISSUE TITLE
渠道号 写入失败

### ISSUE THREAD

**Issue by junqingyi** [Jay-Goo/ProtectedApkResignerForWalle#5]
我可以成功的打出渠道包 但是友盟统计那边渠道号获取不到 全部算到unknown那边去了

**Comment by bugyun** [comment]
#签名，请将原来的代码替换成下面的代码
signShell = buildToolsPath + "apksigner sign --ks "+ keystorePath + " --ks-key-alias " + keyAlias + " --ks-pass pass:'" + keystorePassword + "' --key-pass pass:'" + keyPassword + "' --in " + zipalignedApkPath + " --out " + signedApkPath

**Comment by JinJieGu** [comment]
渠道号获取不到请参看Wiki[ FAQ](https://github.com/Jay-Goo/ProtectedApkResignerForWalle/wiki/FAQ)
