### ISSUE TITLE
可以把channel文件和输出文件的路径都弄在config.py里可配置吗

### ISSUE THREAD

**Issue by xiandanin** [Jay-Goo/ProtectedApkResignerForWalle#7]
能不能像walle那样  可以 在命令上指定打哪些渠道 
`./gradlew clean assembleReleaseChannels -PchannelList=meituan`

**Comment by JinJieGu** [comment]
你的意思是打个别渠道吗？渠道信息放到config会很臃肿，单独抽离出来会更好。单独打某些渠道或者自定义输出文件路径倒是可以考虑升级

**Comment by xiandanin** [comment]
我看`ApkResigner.py`里的`channelFilePath `是固定的，我想把channelFilePath这个变量也可以通过config来配置，还有apk输出路径和加固包源文件路径。
[Pull requests #8](https://github.com/Jay-Goo/ProtectedApkResignerForWalle/pull/8)

还有通过命令单独打某些渠道
